---
dependencies:
  - { role: common }
  - { role: configuration/utf8_locale }
  - { role: ntp_client }
  - { role: iceweasel_latest }
  - { role: binaries/phantomjs }
  - { role: binaries/chromedriver }
  - { role: ruby/rbenv_ruby, ruby_version: jruby-1.7.4, ruby_user: jenkins }
  - { role: ruby/rbenv_ruby, ruby_version: 1.9.3-p448, ruby_user: jenkins }
